- name: gathering facts
  hosts: local 
  connection: local
  tasks:
  - name: print facts 
    ansible.builtin.debug:
     msg: "{{ansible_facts}}"

  - name: check redhat or not
    ansible.builtin.debug:
     msg: "Yes package manager is RedHat"
    when: ansible_facts.os_family == "RedHat"
  - name: check debian or not 
    ansible.builtin.debug:
     msg: "Yes package manger is Debian"
    when: ansible_facts.os_family =="Debian"
