- name: adding loops to make dictionary
  hosts: local
  connection: local
  tasks: 
  - name: install package
    ansible.builtin.package:
      name: "Hello {{item}}"
      state: present
    loop:
    - mysql
    - nginx
    - zip