- name: filters calculation
  hosts: local
  connection: local
  vars:
   topics: linux,shell,ansible,terraform
   tagsMap:
    name: ansible
    project: roboshop
    component: catalogue
    tagList: [
      {
        "key": "name",
        "value": "ansible"
      },
      {
        "key": "project",
        "value": "roboshop"
      },
      {
        "key": "component",
        "value": "catalogue"
      }
    ]
  tasks: 
  - name: greeting
    ansible.builtin.debud:
     msg: "Hi satish, {{Gretting | Default('Good Morning')}}"